runtime: nodejs
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 2
  disk_size_gb: 10

skip_files:
  - ^(.*/)?.*/node_modules/.*$

env_variables:
  PAGE_ACCESS_TOKEN: 'EAAb8It6UorcBAKLeyJACyPneVMZCPI5QefljG22tub4ADOtdKIjtSXKJ5oxWvZCEthRiJzWQYcEZC9iVZCGGV6KQV1JiPx2uhdpAwSaA7wY9YFcaZCvedQfZCxOD4FcnXzp7ObXW37ngLCo1hWofSwBXtkFVsQqUY1A2t6NbRMNsnpQ6x0ty6J'
  VERIFY_TOKEN: 'test_token'
  APP_SECRET: 'e7d1a3dc7cb2d5d0b6f44460a45c295f'
  WIT_TOKEN: 'Y4NCNQPX2VODSBSL63ZSSOK4I4BJZZJN'
  PRODUCTION: true 